@startuml UC_17_ManageServices
title UC_UC_24: Quản lý dịch vụ

left to right direction
skinparam packageStyle rectangle
skinparam usecase {
    BackgroundColor Default
    BorderColor Navy
    ArrowColor Navy
}

actor "Quản trị viên" as A

rectangle "Quản lý Dịch vụ" {
    usecase "Xem Dịch vụ\ntheo Danh mục" as UC1
    usecase "Tạo Dịch vụ" as UC2
    usecase "Bật/Tắt Dịch vụ" as UC3
    usecase "Kiểm tra & Lưu" as UCS
    
    UC2 ..> UCS : <<include>>
    UC3 ..> UCS : <<include>>
}

A --> UC1
A --> UC2
A --> UC3

@enduml
