@startuml UC_15_MovePatientToNextStep
title UC_15: Chuyển sang bước tiếp theo

left to right direction
skinparam packageStyle rectangle
skinparam usecase {
    BackgroundColor Default
    BorderColor Navy
    ArrowColor Navy
}

actor "Bác sĩ" as D

rectangle "Nghiệp vụ Bác sĩ" {
    usecase "Ghi nhận kết quả" as UC14
    usecase "Chuyển sang bước tiếp theo" as UC2
    usecase "Xác nhận hoàn tất Phác đồ\n(Nếu là bước cuối)" as UC3
    
    UC14 ..> UC2 : <<include>>
    UC2 ..> UC3 : <<extend>>
}

D --> UC14

@enduml
