@startuml UC_14_RecordTreatmentResult
title UC_14: Ghi nhận kết quả khám

left to right direction
skinparam packageStyle rectangle
skinparam usecase {
    BackgroundColor Default
    BorderColor Navy
    ArrowColor Navy
}

actor "Bác sĩ" as D

rectangle "Nghiệp vụ Bác sĩ" {

    usecase "Ghi nhận kết quả khám" as UC1
    usecase "Tải lên ảnh Y khoa" as UC2
    usecase "Kê đơn thuốc" as UC3
    usecase "Chuyển bước liệu trình (UC_15)" as UC4
    usecase "Điều chỉnh phác đồ (UC_29)" as UC5

    UC2 ..> UC1 : <<extend>>
    UC3 ..> UC1 : <<extend>>
    UC4 ..> UC1 : <<extend>> : nếu có liệu trình
    UC5 ..> UC1 : <<extend>> : nếu có dịch vụ phát sinh
}

D --> UC1

@enduml