@startuml UC_20_ViewRevenueReports
title UC_UC_27: Xem báo cáo doanh thu

left to right direction
skinparam packageStyle rectangle
skinparam usecase {
    BackgroundColor Default
    BorderColor Navy
    ArrowColor Navy
}

actor "Quản trị viên" as A

rectangle "Báo cáo" {
    usecase "Truy cập Báo cáo Doanh thu" as UC1
    usecase "Lọc theo Ngày/Tháng/Năm" as UC2

    UC1 ..> UC2 : <<include>>
}

A --> UC1

@enduml