@startuml UC08
title UC08: Quản trị viên tạo Phòng khám/Bộ phận mới

left to right direction
skinparam packageStyle rectangle

actor "Quản trị viên (Admin)" as A

rectangle "Quản lý Phòng khám" {
    usecase "Tạo phòng khám mới" as UC8_1
    usecase "Nhập thông tin (Tên, Mô tả)" as UC8_2
    usecase "Lưu vào CSDL" as UC_S
    
    UC8_1 ..> UC8_2 : <<include>>
    UC8_2 ..> UC_S : <<include>>
}

A --> UC8_1

note bottom of UC_S
  Trạng thái mặc định: active = true
end note

@enduml
