@startuml UC09
title UC09: Quản trị viên cập nhật trạng thái Phòng khám

left to right direction
skinparam packageStyle rectangle

actor "Quản trị viên (Admin)" as A

rectangle "Quản lý Phòng khám" {
    usecase "Quản lý trạng thái phòng khám" as UC9
    usecase "Xem danh sách Phòng" as UC9_1
    usecase "Thay đổi trạng thái (Active/Inactive)" as UC9_2
    usecase "Cập nhật vào CSDL" as UC_S

    UC9 ..> UC9_1 : <<include>>
    UC9 ..> UC9_2 : <<include>>
    UC9_2 ..> UC_S : <<include>>
}

A --> UC9

@enduml
