@startuml AC_06_CheckIn
title Activity Diagram: AC_06 Check-in phòng khám

start
:Bệnh nhân đến quầy tiếp đón phòng khám;
if (Bệnh nhân đã đặt lịch hẹn trước?) then (Có)
    :Quét qr hoặc nhập mã checkin tại quầy;
    if (Mã xác thực hợp lệ?) then (Đúng)
        :Hệ thống truy xuất thông tin lịch hẹn;
    else (Sai)
        :Hiển thị lỗi thông báo mã không hợp lệ;
        stop
    endif
else (Không)
    :Tạo lịch hẹn cho khách vãn lai (Walk-in Appointment);
endif
:Check-in thành công;
:Vào hàng đợi chờ đến lượt khám;
stop
@enduml
