@startuml AC_09_ViewMedicalHistory
title Activity Diagram: AC_09 Xem hồ sơ bệnh án cá nhân

start
:Bệnh nhân vào mục Sổ khám bệnh;
:Chọn vào một bệnh án cụ thể;
:Tải chi tiết (Chẩn đoán, thuốc, bác sĩ khám, lời khuyên);
if (Bệnh án có ảnh chụp?) then (Có)
    :Hiển thị ảnh và kết quả xét nghiệm;
else (Không)
endif
stop
@enduml