@startuml
title Activity Diagram: AC_20 Xem Báo cáo doanh thu (Tối giản)

start
:Truy cập Trang chủ (Dashboard);
:Chọn Năm;

if (Có chọn Tháng không?) then (Không)
    :Tính tổng doanh thu cả Năm;

else (Có)
    if (Có chọn Ngày không?) then (Không)
        :Tính tổng doanh thu cả Tháng;
    else (Có)
        :Tính tổng doanh thu của Ngày đã chọn;
    endif
endif
:xem biểu đồ;
stop
@enduml