@startuml AC_24_ProcessQueue
title Activity Diagram: AC_24 Xử lý Hàng đợi chung

start
:Nhận bệnh nhân đến check-in;
:Kiểm tra thông tin;
:Tự động phân bổ bệnh nhân vào hàng đợi  (Join Queue);
:Xem thông tin (View Queue);
stop
@enduml