@startuml UC_03_ManageAccount
title UC_03: Quản lý tài khoản

left to right direction
skinparam packageStyle rectangle
skinparam usecase {
    BackgroundColor Default
    BorderColor Navy
    ArrowColor Navy
}

actor "Bệnh nhân" as P

rectangle "Quản lý tài khoản" {
    usecase "Đăng ký tài khoản" as UC1
    usecase "Xem hồ sơ cá nhân" as UC2
    usecase "Cập nhật thông tin" as UC3
    usecase "Lưu thông tin" as UC4
    
    UC3 ..> UC4 : <<include>>
    UC2 ..> UC3 : <<extend>>
}

P --> UC1
P --> UC2

@enduml
