@startuml UC_02_ForgotPassword
title UC_02: Quên mật khẩu

left to right direction
skinparam packageStyle rectangle
skinparam usecase {
    BackgroundColor Default
    BorderColor Navy
    ArrowColor Navy
}

actor "Bệnh nhân" as P

rectangle "Xác thực" {
    usecase "Quên mật khẩu" as UC1
    usecase "Yêu cầu gửi OTP" as UC2
    usecase "Xác nhận OTP" as UC3
    usecase "Đặt lại mật khẩu" as UC4
    
    UC1 ..> UC2 : <<extend>>
    UC1 ..> UC3 : <<include>>
    UC1 ..> UC4 : <<include>>
}

P --> UC1

@enduml
