@startuml UC_12_ViewPatientMedicalHistory
title UC_UC_15: Xem bệnh án bệnh nhân

left to right direction
skinparam packageStyle rectangle
skinparam usecase {
    BackgroundColor Default
    BorderColor Navy
    ArrowColor Navy
}

actor "Bác sĩ" as D

rectangle "Nghiệp vụ Bác sĩ" {
    usecase "Truy cập hồ sơ bệnh án" as UC1
    usecase "Xem các đơn thuốc cũ" as UC2
    usecase "Kiểm tra Ghi chú y tế\n(Dị ứng/Tiểu sử)" as UC3
    
    UC1 ..> UC2 : <<extend>>
    UC1 ..> UC3 : <<extend>>
}

D --> UC1

@enduml
