@startuml UC_21_ManageInvoices
title UC_UC_28: Quản lý hóa đơn

left to right direction
skinparam packageStyle rectangle
skinparam usecase {
    BackgroundColor Default
    BorderColor Navy
    ArrowColor Navy
}

actor "Quản trị viên" as A

rectangle "Quản lý Hóa đơn" {
    usecase "Xem danh sách Hóa đơn" as UC1
    usecase "Tra cứu/Lọc Hóa đơn" as UC2
    usecase "Mở chi tiết Hóa đơn" as UC3
    
    UC1 ..> UC2 : <<extend>>
    UC1 ..> UC3 : <<extend>>
}

A --> UC1


@enduml
