@startuml UC_07_TrackTreatmentPlan
title UC_07: Theo dõi liệu trình

left to right direction
skinparam packageStyle rectangle
skinparam usecase {
    BackgroundColor Default
    BorderColor Navy
    ArrowColor Navy
}

actor "Bệnh nhân" as P

rectangle "Hồ sơ điều trị" {
    usecase "Xem tiến trình điều trị" as UC1
    usecase "Xem chi tiết các bước" as UC2
    usecase "Xem kết quả, hình ảnh đính kèm" as UC3
    
    UC1 ..> UC2 : <<extend>>
    UC2 ..> UC3 : <<include>>
}

P --> UC1

@enduml
